/**
 * Generates src/environments/environment*.ts from environment variables.
 * For local dev: reads .env.local (never committed).
 * For Netlify: reads process.env set in the Netlify dashboard.
 */
const fs   = require('fs');
const path = require('path');

const envLocalPath = path.join(__dirname, '..', '.env.local');
if (fs.existsSync(envLocalPath)) {
  for (const line of fs.readFileSync(envLocalPath, 'utf8').split('\n')) {
    const m = line.match(/^([^#=\s][^=]*)=(.*)$/);
    if (m) process.env[m[1].trim()] = m[2].trim();
  }
}

const cleanEnvValue = (raw) => {
  if (!raw) return '';
  const lines = raw.split(/[\n,;]/);
  for (let line of lines) {
    line = line.trim();
    if (!line) continue;
    
    // If the line is just a URL, don't treat colons in it as separators
    if (/^(https?|ftp):\/\//i.test(line)) {
      return line.replace(/^['"]|['"]$/g, '').trim();
    }
    
    const match = line.match(/^(?:[a-zA-Z_]\w*\s*[:=]\s*)(.+)$/);
    let candidate = match ? match[1].trim() : line;
    candidate = candidate.replace(/^['"]|['"]$/g, '').trim();
    if (candidate) {
      return candidate;
    }
  }
  return '';
};

const get = key => {
  const v = process.env[key];
  if (!v) console.warn(`⚠️  Missing env var: ${key}`);
  return cleanEnvValue(v);
};

const make = (prod) => `// Auto-generated by scripts/set-env.js — do not edit manually
export const environment = {
  production: ${prod},
  firebaseConfig: {
    apiKey:            ${JSON.stringify(get('FIREBASE_API_KEY'))},
    authDomain:        ${JSON.stringify(get('FIREBASE_AUTH_DOMAIN'))},
    projectId:         ${JSON.stringify(get('FIREBASE_PROJECT_ID'))},
    storageBucket:     ${JSON.stringify(get('FIREBASE_STORAGE_BUCKET'))},
    messagingSenderId: ${JSON.stringify(get('FIREBASE_MESSAGING_SENDER_ID'))},
    appId:             ${JSON.stringify(get('FIREBASE_APP_ID'))},
    measurementId:     ${JSON.stringify(get('FIREBASE_MEASUREMENT_ID'))},
  },
  googleClientId: ${JSON.stringify(get('GOOGLE_CLIENT_ID'))},
};
`;

const dir = path.join(__dirname, '..', 'src', 'environments');
fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(path.join(dir, 'environment.ts'),      make(false));
fs.writeFileSync(path.join(dir, 'environment.prod.ts'), make(true));
console.log('✅  environment.ts and environment.prod.ts generated.');
