/**
 * Generates src/environments/environment*.ts from environment variables.
 * For local dev: reads .env.local (never committed).
 * For Netlify: reads process.env set in the Netlify dashboard.
 */
const fs   = require('fs');
const path = require('path');

const envLocalPath = path.join(__dirname, '..', '.env.local');
if (fs.existsSync(envLocalPath)) {
  for (const line of fs.readFileSync(envLocalPath, 'utf8').split('\n')) {
    const m = line.match(/^([^#=\s][^=]*)=(.*)$/);
    if (m) process.env[m[1].trim()] = m[2].trim();
  }
}

const get = key => {
  const v = process.env[key];
  if (!v) console.warn(`⚠️  Missing env var: ${key}`);
  return v || '';
};

const make = (prod) => `// Auto-generated by scripts/set-env.js — do not edit manually
export const environment = {
  production: ${prod},
  firebaseConfig: {
    apiKey:            '${get('FIREBASE_API_KEY')}',
    authDomain:        '${get('FIREBASE_AUTH_DOMAIN')}',
    projectId:         '${get('FIREBASE_PROJECT_ID')}',
    storageBucket:     '${get('FIREBASE_STORAGE_BUCKET')}',
    messagingSenderId: '${get('FIREBASE_MESSAGING_SENDER_ID')}',
    appId:             '${get('FIREBASE_APP_ID')}',
    measurementId:     '${get('FIREBASE_MEASUREMENT_ID')}',
  },
  googleClientId: '${get('GOOGLE_CLIENT_ID')}',
};
`;

const dir = path.join(__dirname, '..', 'src', 'environments');
fs.writeFileSync(path.join(dir, 'environment.ts'),      make(false));
fs.writeFileSync(path.join(dir, 'environment.prod.ts'), make(true));
console.log('✅  environment.ts and environment.prod.ts generated.');
